"""add_created_by

Revision ID: 10c28eda32c4
Revises: 971023bbed51
Create Date: 2021-10-13 12:05:41.765916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10c28eda32c4'
down_revision = '971023bbed51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Account', sa.Column('created_by', sa.String(length=255), nullable=True))
    op.add_column('Account', sa.Column('updated_by', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Account', 'updated_by')
    op.drop_column('Account', 'created_by')
    # ### end Alembic commands ###
