"""add_login

Revision ID: 2d695461d3d2
Revises: 5c88bf991330
Create Date: 2021-10-08 01:21:54.749222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d695461d3d2'
down_revision = '5c88bf991330'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Account', sa.Column('login', sa.String(length=50), nullable=True))
    op.create_unique_constraint(None, 'Account', ['login'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Account', type_='unique')
    op.drop_column('Account', 'login')
    # ### end Alembic commands ###
