"""add_password

Revision ID: 971023bbed51
Revises: 2d695461d3d2
Create Date: 2021-10-11 23:49:38.124051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '971023bbed51'
down_revision = '2d695461d3d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Account', sa.Column('password', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Account', 'password')
    # ### end Alembic commands ###
